six_dof_hand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  x_linear_actuator_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: x_linear_actuator_joint
    pid: {p: 100.0, i: 0.01, d: 50}
  y_linear_actuator_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: y_linear_actuator_joint
    pid: {p: 100.0, i: 0.01, d: 50}
  z_linear_actuator_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: z_linear_actuator_joint
    pid: {p: 100.0, i: 0.01, d: 50}
  x_rotary_actuator_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: x_rotary_actuator_joint
    pid: {p: 100.0, i: 0.01, d: 50}
  y_rotary_actuator_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: y_rotary_actuator_joint
    pid: {p: 100.0, i: 0.01, d: 50}
  z_rotary_actuator_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: z_rotary_actuator_joint
    pid: {p: 100.0, i: 0.01, d: 50}
  r_finger_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_finger_joint
    pid: {p: 100.0, i: 0.01, d: 50}
  l_finger_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_finger_joint
    pid: {p: 100.0, i: 0.01, d: 50}
